# **NumPy Arrays**

In [1]:
import numpy as np
my_list=[1,2,3]

In [46]:
arr=np.array(my_list)
#converts the list into array

In [47]:
arr
#show the array

array([1, 2, 3])

In [48]:
matrix_list=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix=np.array(matrix_list)
#nested lists make a matrix

In [49]:
my_matrix
#show the matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.arange(0,11)
#the arange() function is just like the range() function
#(start,stop,step) start inclusive, but stop exclusive

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [51]:
np.zeros(4)
#makes an array of n zeros (1D unless passed a tuple)

array([0., 0., 0., 0.])

In [52]:
np.zeros((4,4))
#when passed a tuple, it creates a 2D array (matrix)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [54]:
np.ones(13)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
#linspace generates evenly spaced numbers over a specified intervals
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [57]:
np.linspace(0,5,10)*12

array([ 0.        ,  6.66666667, 13.33333333, 20.        , 26.66666667,
       33.33333333, 40.        , 46.66666667, 53.33333333, 60.        ])

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [61]:
np.random.rand(3)
#generates n random numbers all in between 0 and 1 (but not including 1).
#normalized - between 0 and 1

array([0.90600459, 0.03389179, 0.05487694])

In [18]:
np.random.rand(3,3)
#generates a matrix of random numbers between 0 and 1

array([[0.34707628, 0.95710044, 0.85276985],
       [0.82780143, 0.6513202 , 0.0525575 ],
       [0.50116577, 0.12405062, 0.99880276]])

In [19]:
np.random.randn(4)

array([-0.32498097, -0.63807584,  0.52587972,  2.66981237])

In [20]:
np.random.randn(3,3)

array([[-0.92076295,  0.39445379, -0.36101436],
       [-1.83996924,  0.65326852,  0.39730687],
       [-0.17519801, -0.54278419,  0.15952843]])

In [21]:
np.random.randint(1,100)

20

In [22]:
np.random.randint(1,100,4)

array([ 7, 43,  8, 66])

In [23]:
arr=np.arange(25)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
ranarr=np.random.randint(0,50,10)

In [26]:
ranarr

array([15,  6, 34, 43, 14, 18, 40, 26, 46, 26])

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
ranarr.max()

46

In [29]:
ranarr.min()

6

In [30]:
ranarr.argmax()

8

In [31]:
ranarr.argmin()

1

In [32]:
arr.shape

(25,)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
arr=arr.reshape(5,5)

In [35]:
arr.shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

# **Indexing and Selection**

In [37]:
arr=np.arange(1,25,2)

In [38]:
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [39]:
arr[3]

7

In [40]:
arr[1:5]

array([3, 5, 7, 9])

In [41]:
arr[::-1]

array([23, 21, 19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [42]:
arr[:6]

array([ 1,  3,  5,  7,  9, 11])

In [43]:
arr[5:]

array([11, 13, 15, 17, 19, 21, 23])

In [44]:
arr[0:5]=100

In [45]:
arr

array([100, 100, 100, 100, 100,  11,  13,  15,  17,  19,  21,  23])